theme = "LoveIt"
title = "AG website"
ignoreErrors = [
"error-remote-getjson",
"error-missing-instagram-accesstoken"
]


[caches.images]
dir = ":cacheDir/images"


[markup.goldmark.renderer]
unsafe = true


[[menu.main]]
weight = 1
identifier = "posts"
pre = "📚"
name = "Posts"
url = "/posts/"


[[menu.main]]
weight = 1
identifier = "about"
pre = "🫆"
name = "About me"
url = "/about/"


[params]
defaultTheme = "auto"
title = "Andres Gaona"


[params.author]
name = "Andres Gaona"
email = "adgaona7@gmail.com"
link = ""


[params.header]
desktopMode = "fixed"
mobileMode = "auto"


[params.header.title]
logo = ""
name = "Andrés Gaona"
pre = ""
post = ""
typeit = false


[params.footer]
enable = true
custom = ""
hugo = false
copyright = true
author = true
since = 2_019
icp = ""


[params.home]
rss = 10


[params.home.profile]
enable = true
avatarURL = "images/avatar.png"
title = ""
subtitle = "Robotics engineer building intelligent real-time robotic systems."
typeit = true
social = true
disclaimer = ""


[params.home.posts]
enable = true
paginate = 6
defaultHiddenFromHomePage = false


[params.social]
GitHub = "andresgaona7"
